import {
  Sparkles,
  ShieldCheck,
  TriangleAlert,
  TrendingUp,
  Cpu,
  ArrowRight,
} from "lucide-react";

const insights = [
  {
    icon: ShieldCheck,
    title: "Asset Health",
    value: "97%",
    desc: "Most enterprise assets are operating normally.",
    color: "bg-emerald-500/15 text-emerald-400",
  },
  {
    icon: TriangleAlert,
    title: "Maintenance Alerts",
    value: "12",
    desc: "Assets require maintenance within 7 days.",
    color: "bg-yellow-500/15 text-yellow-400",
  },
  {
    icon: TrendingUp,
    title: "Performance",
    value: "+18%",
    desc: "Improved compared to the previous month.",
    color: "bg-indigo-500/15 text-indigo-400",
  },
];

export default function AIInsights() {
  return (
    <div className="rounded-3xl border border-zinc-800 bg-gradient-to-br from-zinc-900 to-zinc-950 p-7 shadow-lg">

      {/* Header */}

      <div className="mb-7 flex items-center justify-between">

        <div>

          <h2 className="text-2xl font-bold text-white">
            AI Insights
          </h2>

          <p className="mt-1 text-sm text-zinc-500">
            Smart recommendations generated by AssetIQ AI
          </p>

        </div>

        <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-600">

          <Cpu className="text-white" size={22} />

        </div>

      </div>

      {/* Cards */}

      <div className="space-y-4">

        {insights.map((item) => {
          const Icon = item.icon;

          return (
            <div
              key={item.title}
              className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5 transition-all duration-300 hover:border-indigo-500 hover:bg-zinc-800"
            >

              <div className="flex items-center justify-between">

                <div className="flex items-center gap-4">

                  <div
                    className={`flex h-12 w-12 items-center justify-center rounded-xl ${item.color}`}
                  >
                    <Icon size={22} />
                  </div>

                  <div>

                    <h3 className="font-semibold text-white">
                      {item.title}
                    </h3>

                    <p className="text-sm text-zinc-500">
                      {item.desc}
                    </p>

                  </div>

                </div>

                <h3 className="text-2xl font-bold text-white">
                  {item.value}
                </h3>

              </div>

            </div>
          );
        })}

      </div>

      {/* AI Recommendation */}

      <div className="mt-7 rounded-2xl border border-indigo-500/20 bg-indigo-600/10 p-5">

        <div className="flex items-center gap-3">

          <Sparkles
            className="text-indigo-400"
            size={22}
          />

          <h3 className="font-semibold text-white">
            AI Recommendation
          </h3>

        </div>

        <p className="mt-4 leading-7 text-zinc-300">
          Battery Pack <strong>#23</strong> has a high probability of
          failure within the next <strong>5 days</strong>. Schedule
          preventive maintenance to avoid unexpected downtime.
        </p>

        <button className="mt-6 flex items-center gap-2 font-medium text-indigo-400 transition hover:translate-x-1">

          View Recommendation

          <ArrowRight size={18} />

        </button>

      </div>

    </div>
  );
}